{% set name = "fludashboard" %}
{% set version = "0.4.0" %}
{% set sha256 = "03dfdcc7b3817234855166490bde38d75313ac45579c226b0fc9bca0848f745a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [py2k or py34 or win]

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - pandas >=0.21
    - numpy
    - flask
    - unidecode
    - psycopg2
    - sqlalchemy
    - pyyaml
    - cufflinks-py
    - plotly 2.5.1
    - ipython

test:
  imports:
    - fludashboard

about:
  home: https://github.com/FluVigilanciaBR/fludashboard
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Interactive dashboard for exploring influenza incidence data'
  description: |
    Flu Dashboard is an initiative to monitor and provide alert levels for
    Severe Acute Respiratory Infections (SARI) notifications registered at SINAN,
    the Brazilian Notifiable Diseases Information System (www.saude.gov.br/sinan) Data
    is provided for each Brazilian State as well as by influenza-like illnessess (ILI) regions.
    This is a product of the joint work between researchers at the Scientific Computation Program
    at Oswaldo Cruz Foundation (Fiocruz, PROCC), School of Applied Mathematics
    at Fundação Getúlio Vargas (EMAp-FGV), both from Rio de Janeiro, Brazil,
    and the Inluenza Work Force at the Health Surveillance Secretariat of
    the Brazilian Ministry of Health (GT-Influenza, SVS, MS).
  doc_url: https://fludashboard.readthedocs.io/en/latest/
  dev_url: https://github.com/FluVigilanciaBR/fludashboard

extra:
  recipe-maintainers:
    - xmnlab
    - marfcg
