appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: clatdtKbBRk4Y+1QCJLFyn90tKSq2mUhieWPcIX6+jypV+a5/w+gTmLftLk6dOI7DKJic2qd6fecFEkmp8RpEScIl+1bT/8PjcNhXDRhc3qeQrYvtwkl8aPRrLNlmJBO/Ic9yTj/0sYR/aTKvpYsjMsks8htbWuahs6M4WCMHI03cpRKu0xtQHotJr4I38fHwqlnOq+WWiaN0Fb5CXok4SACol5G3ogfB263GjVFvOA+oGkYI4DNcLCl3iUdewKkrxF7CxMs27hhs/fK5BO3PlXucczvY0vr+FNDAiBJblBokmXgdU/P7btHQsNCs3PtBl0Fn/gEpYamsGzw/+jfa+HtwDUR/+RSL2a16NmxHa7SHLa6m1IHNstQa+DTCjl4S1LAcNRW/Y4ep2hpt/M4tMyJlQiKGF93+ir8TsMACgh7ndiDI0U/MflNeZyzYqaiQk7J/DMiW+tXsx+wY7LyY8DLci/Q3oJTas3GaREmtmcsEMQa5JbEZtQbdH6CqjU+bnqCI0+ZxWy2Wv3HaJTsAYzTyvxmLYv5UG4IzXiGUt87WtwU+4Y9RKNzx/YBoID83I2AepAWWAB+7Rb+0aJnjwxWWNxAJunT9YJD05juyFnylJSf9e5hHjWiu8N0Z+WzIuoQ6iHZO2GuFjelXbBazzmxEjfYJ79NHEclDRO/NoU=}
